baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Ananth Sridhar"
  subtitle    = "Curious mind"
  copyright   = "© 2018"

  cover       = "img/blog-cover.jpg"
  description = "Anantharaghavan Sridhar's personal website."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  # twitterName = "faketryghost"
  # fbName = "RaghavanS"
  githubName = "saraghav"
  linkedinName = "AnanthRSridhar"
  # mediumName = ""

  # logo = "hugo-logo.png"
  # orgName = "EM"
  # orgWebsite = "https://www.telematika.org"
  # orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "Ananth Sridhar"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "San Francisco, CA"
  authorWebsite = "https://saraghav.github.io"
  authorDescription = "Curious mind. Software Engineer."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

# [[menu.main]]
#   name = "Go"
#   url = "/tags/golang/"
#   weight = 100
 
[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

# [[menu.main]]
#   name = "External"
#   url = "https://google.com/"
#   weight = 95

